Processing data
ahmedeid6842/Blog_Rails pull request #2
Opened 2023-09-20 18:14 UTC by ahmedeid6842

## Description: :speech_balloon: 
This pull request introduces the necessary code changes to fulfill the project requirements. 🔨 It creates model classes for all entities mentioned in the provided ERD diagram and establishes the required associations between the models. 

🤝 The `author_id` column in the posts table is set as the foreign key for the users table. 🔑 Additionally, custom methods are implemented in the models to enhance functionality and fulfill the specified requirements. 🚀

## Done tasks: :white_check_mark: 
- [x] Created model classes for all entities  🎉👍
- [x] Established associations between models 🤝
- [x] Implemented custom methods in the models  🛠️
- [x] Added the `author_id` foreign key in the `comments` table  🔑
- [x] Updated the `update_post_comments_counter` method in the `Comment` model  📈
- [x] Updated the `update_post_likes_counter` method in the `Like` model  📈
- [x] Updated the `update_user_posts_counter` method in the `Post` model  📈

## Highlights: :dart: 
- The code changes address the project requirements by creating the necessary models and associations.  ✅
- Custom methods have been implemented to fulfill the requirements, such as retrieving recent posts for a user and updating counters for likes, comments, and posts.  🚀
- The addition of the `author_id` foreign key in the `comments` table enables proper association between comments and users. 🔗

## ⭐To the code reviewer 👨‍💻

💝 We really thank 🙇‍♂️ you, dear code reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check the PR 🧾 .

We kindly ask 🙏 dear code reviewer 🤵 that if there is any kind of issue 🦯 in this project, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some big issues are essential to be changed ♻️ please kindly contact 📞 us through Zoom or Slack, We're available on Microverse UTC-6 time zone.   

--- 
<p align="center"> @ahmedeid6842 </p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/57197702/235438155-a0422937-6810-4e50-b887-9e20e5e49270.gif" alt="200w">
</p>

2023-09-20 18:35 UTC, danmainah requested changes
Hi @ahmedeid6842 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is missing the future features and acknowledgement sections in the readme also the linter setup only shows rubocop check instead of rubocop and  Stylelint, kindly ensure you have the right linter setup for rails projects.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-20 19:20 UTC, Ibizugbe requested changes
Hi @ahmedeid6842 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/ahmedeid6842/Blog_Rails/assets/64643995/d4a42b48-2542-44ee-8dff-4be2878f5eb5)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] `User`, `Post`, `Comment` and `Like` models are created  inside `app/models/` directory👍🏼.
- [x] A model that returns 3 most recent posts has been created👍🏼. 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 19:20 UTC, Ibizugbe commented on app/models/like.rb
> +  belongs_to :user
Just as implemented in the comment model, a like should belong to an author😉. kindly fix that👍🏼.
```suggestion
belongs_to :author, class_name: 'User'
```

2023-09-21 00:33 UTC, Abenezer-Tilahun commented on app/models/like.rb
> +  belongs_to :user
Fixed.

2023-09-21 00:42 UTC, ahmedeid6842 commented on app/models/like.rb
> +  belongs_to :user
Hi @Abenezer-Tilahun  :wave: 
I don't understand you review you just leaved "Fixed" which is unclear for me because I already fixed the mention comment that was provided by @Ibizugbe. :mag:

2023-09-21 00:53 UTC, Abenezer-Tilahun approved these changes
Hi @ahmedeid6842 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2023-09-21 00:53 UTC, Abenezer-Tilahun commented on app/models/post.rb
> +  end
- [ Optional ] Kindly I recommend you to use  [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - `after_save` to call the `#update_user_posts_counter` method every time a new post has been saved to database, then make the `update_user_posts_counter` method private just like the below sample Instead of using  `after_create` because **after_create** is only invoked when a new record is created and saved to the database for the first time but **after_save** is invoked every time a record is saved to the database, whether it is a new record or an existing record that is updated.

```
def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

after_save :update_user_posts_counter

private
  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

```

2023-09-21 00:53 UTC, Abenezer-Tilahun commented on app/models/comment.rb
> +  end
- [ Optional ] Good Job for using [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - `after_save` to call the `#update_post_comments_counter` method every time a new comment has been saved to database, then **Kindly I recommend you to make the `update_post_comments_counter` method private**.

2023-09-21 00:53 UTC, Abenezer-Tilahun commented on app/models/like.rb
> +  end
- [ Optional ] Good Job for using [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - `after_save` to call the `#update_post_likes_counter` method every time a new like has been saved to database, then **Kindly I recommend you to make the `update_post_likes_counter` method private**.

2023-09-21 00:55 UTC, Abenezer-Tilahun commented on app/models/like.rb
> +  belongs_to :user
Hello @ahmedeid6842 When I commented Fixed Means that   I wanted to mention that you fixed the suggested changes requested by the previous reviewer.

2023-09-21 00:59 UTC, ahmedeid6842 commented on app/models/like.rb
> +  belongs_to :user
Okay got it :+1: 

Thanks again for your review, But it would be better to mention it in your review as _[Optional changes]_ rather than write "Fixed" in a comment. 

But again many thanks for you time and effort to review my code :pray: , you review is very valuable and awesome. Many thanks @Abenezer-Tilahun :100: :heart_decoration:

2023-09-21 19:41 UTC, ahmedeid6842 commented
# 🎉🎉🥳🥳

![7fb4d55fa09fc4f5426e6d5934d1d02f](https://user-images.githubusercontent.com/57197702/236395820-a300cb53-2cec-4d36-922d-b42a3288501f.gif)

2023-09-21 19:41 UTC, merged