Milestone: add form to create a post & comment :writing_hand: :bookmark_tabs:
ahmedeid6842/Blog_Rails pull request #7
Opened 2023-09-29 02:37 UTC by ahmedeid6842

## Description: :speech_balloon: 
At this pull request I added the functionality of creating a post, comment and like a post through adding the appropriate controllers and views

## Done: :white_check_mark: 
- [x] Create a `current_user` function to get the data of the first user. 
- [x] Implement a controller for creating a post.
- [x] Implement a controller for creating a comment and assign it to a post.
- [x] Implement a controller for adding a likes to  a post.  
- [x] Create create a post and comment form, and assign the author of a post to the current user. 
- [x] Make the user able to like a post.

#### Thanks in advance to the reviewer for taking time and effort to review my code. :pray: :heart_decoration: 
--- 
<p align="center"> @ahmedeid6842 </p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/57197702/235438155-a0422937-6810-4e50-b887-9e20e5e49270.gif" alt="200w">
</p>

2023-09-29 05:24 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @ahmedeid6842 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Posts and comments are created on behalf of the currently logged in user :+1: 

## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 05:24 UTC, FrederickMih commented on app/views/posts/new.html.erb
> +        <% end %>
- [ ] Two inputs are required to create a post: **Title** and **Text** unfortunately you only provide the user with the title field. Please fix this issue.
![Screenshot from 2023-09-29 06-03-48](https://github.com/ahmedeid6842/Blog_Rails/assets/63087491/91afa14c-82ab-461d-9b94-380460f9ef33)

2023-09-29 05:24 UTC, FrederickMih commented on app/controllers/comments_controller.rb
> +class CommentsController < ApplicationController
- [ ] To add a comment for a post, it is advisable to add two essentials `new` and `create` :+1:  actions here. You didn't add the `new` action. You needs this new action so that you should add the form for creating comment for a post at app/views/comments/new.html.erb :+1: This way, it would be easier to extend your code in the future without worries.

2023-09-29 05:24 UTC, FrederickMih commented on config/routes.rb
> +      resources :comments
- [ ] As mentioned above :arrow_up: , you'll need a pair of routes for creating comments and posts. **Hints** `resources :posts, only: [:new, :create]`

2023-09-29 05:24 UTC, FrederickMih commented on config/routes.rb
> +      resources :likes
- [ ] Here also, there should be a route for creating likes

2023-09-29 05:27 UTC, FrederickMih commented
Hi @ahmedeid6842, right now every Rails command forces the help messages to display on the console. I think this is because the bin folder is missing at the root of the application directory. I'll kindly advice you to add this folder to it becomes easier to set up your app locally :+1:

2023-09-29 22:54 UTC, ahmedeid6842 commented
> Hi @ahmedeid6842, right now every Rails command forces the help messages to display on the console. I think this is because the bin folder is missing at the root of the application directory. I'll kindly advice you to add this folder so it becomes easier to set up your app locally 👍

Thanks for the review, I already have the bin folder locally

2023-09-29 22:55 UTC, ahmedeid6842 commented on config/routes.rb
> +      resources :likes
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on config/routes.rb
> +      resources :comments
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on app/controllers/comments_controller.rb
> +class CommentsController < ApplicationController
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on app/views/posts/new.html.erb
> +        <% end %>
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on app/views/users/index.html.erb
> +    <h2>Current User: <%= @current_user.name %>
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on config/routes.rb
> +  resources :posts
fixed

2023-09-29 22:55 UTC, ahmedeid6842 commented on config/routes.rb
> +  resources :posts
fixed

2023-09-30 01:44 UTC, ichala reviewed
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 01:56 UTC, merged